# Example configuration file for strainer

[api]
# Provider configuration using type-safe enum
provider_config = { type = "anthropic", model = "claude-2", max_tokens = 100000 }

# API key (can also be set via STRAINER_API_KEY environment variable)
api_key = "${ANTHROPIC_API_KEY}"

# Optional custom base URL
base_url = "https://api.anthropic.com/v1"

[limits]
# Rate limits (per minute)
requests_per_minute = 60
tokens_per_minute = 100000

[process]
# Process control thresholds
pause_on_warning = false
pause_on_critical = true

[thresholds]
warning = 80
critical = 95
resume = 70

[backoff]
min_seconds = 1
max_seconds = 60

[logging]
level = "info"
format = "json"