# Example configuration file for strainer

[api]
# API provider (currently only supports "anthropic")
provider = "anthropic"
# API key (can also be set via STRAINER_API_KEY environment variable)
api_key = "${ANTHROPIC_API_KEY}"
# Optional custom base URL
base_url = "https://api.anthropic.com/v1"

# Provider-specific settings
[api.provider_specific]
model = "claude-2"
max_tokens = 100000
temperature = 0.7

[limits]
# Rate limits (per minute)
requests_per_minute = 60
tokens_per_minute = 100000

[process]
# Process control thresholds
warning_threshold = 80
critical_threshold = 95
pause_on_critical = true
resume_threshold = 70

[logging]
level = "info"
format = "json"
