# Minimal configuration example
# Only required fields are specified

[api]
# Provider configuration using type-safe enum
provider_config = { type = "anthropic" }  # Uses default model and max_tokens

# API key (can also be set via STRAINER_API_KEY environment variable)
api_key = "${ANTHROPIC_API_KEY}"

# Only limit requests, ignore token counts
[limits]
requests_per_minute = 100

# Use default thresholds and backoff settings